"""empty message

Revision ID: 0524ea6a9689
Revises: 5469fb88b465
Create Date: 2023-04-26 04:21:49.635306

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0524ea6a9689"
down_revision = "5469fb88b465"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("total_calories", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("total_fat", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("total_carbs", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("total_protein", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meal_product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("meal_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity_grams", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_product")
    op.drop_table("meal")
    # ### end Alembic commands ###
