"""empty message

Revision ID: 1458f256cf80
Revises: 831930d8cdbb
Create Date: 2023-04-20 12:58:40.912469

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1458f256cf80"
down_revision = "831930d8cdbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("calories", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("fat", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("carbs", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("protein", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("upvotes", sa.INTEGER(), nullable=False),
        sa.Column("downvotes", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
