"""empty message

Revision ID: 5469fb88b465
Revises: 1458f256cf80
Create Date: 2023-04-21 17:25:09.597073

"""
import sqlalchemy as sa
import sqlalchemy_utils.types.choice

from alembic import op
from app.apis.utils.enums import HeightMetric, WeightMetric

# revision identifiers, used by Alembic.
revision = "5469fb88b465"
down_revision = "1458f256cf80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "pref_height_metric",
            sqlalchemy_utils.types.choice.ChoiceType(HeightMetric),
            server_default="cm",
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("height", sa.FLOAT(decimal_return_scale=2), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "pref_weight_metric",
            sqlalchemy_utils.types.choice.ChoiceType(WeightMetric),
            server_default="kg",
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("weight", sa.FLOAT(decimal_return_scale=2), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column("target_weight", sa.FLOAT(decimal_return_scale=2), nullable=True),
    )
    op.add_column("user", sa.Column("target_calories", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "target_calories")
    op.drop_column("user", "target_weight")
    op.drop_column("user", "weight")
    op.drop_column("user", "pref_weight_metric")
    op.drop_column("user", "height")
    op.drop_column("user", "pref_height_metric")
    # ### end Alembic commands ###
