# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: ^(vision-canvas-web/|docs/)
      - id: end-of-file-fixer
        exclude: ^(vision-canvas-web/|docs/)
      - id: trailing-whitespace
        exclude: ^(vision-canvas-web/|docs/)

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^(vision-canvas-web/|docs/)
        args: [ --line-length=120 ]
