-- Create Tables
CREATE TABLE regions
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    region_name VARCHAR2(3) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    team_name VARCHAR2(100) NOT NULL,
    region_id NUMBER        NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE roles
(
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_name VARCHAR2(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE players
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    summoner_name VARCHAR2(50) NOT NULL,
    role_id       NUMBER       NOT NULL,
    region_id     NUMBER       NOT NULL,
    team_id       NUMBER       NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES roles (id),
    FOREIGN KEY (region_id) REFERENCES regions (id),
    FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE tournaments
(
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tournament_name VARCHAR2(100) NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    location        VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE matches
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tournament_id NUMBER NOT NULL,
    team1_id      NUMBER NOT NULL,
    team2_id      NUMBER NOT NULL,
    match_date    DATE   NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (tournament_id) REFERENCES tournaments (id),
    FOREIGN KEY (team1_id) REFERENCES teams (id),
    FOREIGN KEY (team2_id) REFERENCES teams (id)
);

CREATE TABLE match_results
(
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    match_id        NUMBER NOT NULL,
    winning_team_id NUMBER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (match_id) REFERENCES matches (id),
    FOREIGN KEY (winning_team_id) REFERENCES teams (id),
    UNIQUE (match_id)
);

CREATE TABLE player_statistics
(
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    player_id NUMBER NOT NULL,
    match_id  NUMBER NOT NULL,
    kills     NUMBER NOT NULL,
    deaths    NUMBER NOT NULL,
    assists   NUMBER NOT NULL,
    cs        NUMBER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (player_id) REFERENCES players (id),
    FOREIGN KEY (match_id) REFERENCES matches (id),
    UNIQUE (player_id, match_id)
);

CREATE TABLE champions
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    champion_name VARCHAR2(50) NOT NULL,
    role_id       NUMBER       NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE champion_picks
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    match_id    NUMBER NOT NULL,
    player_id   NUMBER NOT NULL,
    champion_id NUMBER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (match_id) REFERENCES matches (id),
    FOREIGN KEY (player_id) REFERENCES players (id),
    FOREIGN KEY (champion_id) REFERENCES champions (id),
    UNIQUE (match_id, player_id)
);

CREATE TABLE bans
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    match_id    NUMBER NOT NULL,
    champion_id NUMBER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (match_id) REFERENCES matches (id),
    FOREIGN KEY (champion_id) REFERENCES champions (id),
    UNIQUE (match_id, champion_id)
);
